spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe-app
    username: root
    password: admin
    platform: myslq
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            script:
#              action: create
#              create-target: