spring:
  datasource:
    url: jdbc:mysql:localhost:3306/recipe-app
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false